Locales ['dk'] = {
  ['valid_purchase'] = 'Vil du købe?',
  ['yes'] = 'Ja (<span style="color: green;">kr.%s</span>)',
  ['no'] = 'Nej',
  ['helmet'] = 'Hjelm / Hat',
  ['glasses'] = 'Briller',
  ['mask'] = 'Maske',
  ['ears'] = 'Tilbehør Øre',
  ['shop'] = '%s butik',
  ['set_unset'] = 'Tag på / Tag af',
  ['not_enough_money'] = 'Du har ikke nok penge',
  ['press_access'] = 'Tryk ~INPUT_CONTEXT~ for at tilgå menuen',
  ['accessories_blip'] = 'Tilbehør',
  ['no_ears'] = 'Du har ikke noget tilbehør til ørene',
  ['no_glasses'] = 'Du har ingen briller',
  ['no_helmet'] = 'Du har ingen hjelm',
  ['no_mask'] = 'Du har ikke en maske',
  ['you_paid'] = 'Du betalte ~g~kr.%s~s~',
}
